KWHSPH ~ FUELHEAT + REPORTABLE_DOMAIN + ELECAUX + HDD65 + PELHEAT + 
    TYPEHUQ + EQUIPM + EQMAMT + USENG + AIA_Zone + UR + CARRYEL + 
    FOPAY + PGASHEAT + DRAFTY + Climate_Region_Pub + CDD65 + 
    LPWARM + ESFRIG + PGASHTWA + UGOTH + PELHOTWA + CONVERSION + 
    TYPEHUQ4 + YEARMADERANGE + NCOMBATH + FOOTHER + FUELTUB + 
    SIZRFRI1 + BASEHT2 + USENOTMOIST + BATTOOLS + 
    OUTGRILLFUEL + USELP + AGECENAC + HHSEX + USEWWAC + COOLTYPENOAC + 
    REPLCCAC + HELPWS + STOVEFUEL + TELLDAYS + UGASAUX + USENGFP + 
    LGT12 + HEATROOM + NHSLDMEM + BASEUSE + DEFROST + SIZFREEZ2 + 
    OTHWORK + ANSMACH + OTHERWAYEL + NUMTHERM + PROTHERM + WHEATAGE2 + 
    OVENFUEL + INVESTMT + NAPTFLRS + LGT1 + WOODLOGS + LPCOOK + 
    METROMICRO + WDWARM + ACOTHERS + HELPWSY + FREEZER2 + NUMFREEZ + 
    TOASTER + RANGE + WARMAIR + DIFFUEL + LPGAUX + VCR3 + WELLPUMP + 
    PRKGPLC2 + ATTCCOOL + TVONWE2 + COMBODVR2 + RENTHELP + TVSIZE1 + 
    WASHLOAD + TEMPHOME + REPLCWWAC + HELPHTY + TVONWD3 + MAINTAC + 
    TVAUDIOSYS2 + TVAUDIOSYS1 + MAINTHT + CRAWL + WHEATOTH + 
    HEATOTH + H2OTYPE1 + STUDIO + NUMAPTS + STOVEN + NUMFRIG + 
    NUMCORDS