---
title: "Predicting electricity demand for space heating in US households"
subtitle: "Project report in Linear Statistical Models (MVE190)"
author: "Joel Goop"
date: \today
link-citations: true
output: 
  bookdown::pdf_document2:
    citation_package: natbib
    number_sections: true
    includes:
      in_header: header.tex
documentclass: article
classoption: a4,11pt
geometry: margin=3cm
toc: false
biblio-style: "unsrtnat"
bibliography: "proposal-refs.bib"
---

```{r setup, include=FALSE}
library(ggplot2)
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)

source("clean_data.R")
load("tree-used.RData")
load("lm-used.RData")
```

# Introduction

Roughly one third of the energy consumed in both commercial and residential bildings is used for space heating [@ipcc2014]. It is important to be able to predict this energy demand and to understand the factors that influence it, for example for forecasting changes in the energy demand based on changes in the building stock or policy measures such as building standards. Several different energy sources are used for space heating, but in this report, I focus on electricity. I aim to construct predictive models for electricity consumption for space heating in US households based on the Residential Energy Consumption Survey dataset @recs. 

# Description of the data

The selected dataset contains responses from \num{12083} households to detailed survey questions regarding their energy consumption and expenditures, as well as their housing situation. The data collected is for the year 2009.

The total number of columns in the original dataset is \num{931}, but out of these, \num{361} are id, statistical weight, or imputation flags for other variables\footnote{Set to \num{1} if the value for the variable in question has been imputed for that particular row and \num{0} if it has not.}. For this analysis, the imputation flag columns have simply been removed and imputed values have been used as if they were valid data points. Another \num{91} columns are directly related to energy consumption or expenditures, excluding our dependent variable, and are also removed, since they could not be expected to be available when actual predictions are to be made. Further, columns with a variance $<0.01$ are dropped, leaving \num{458} variables including the dependent `KWHSPH`. \num{56} numeric (non-categorical) variables are identified manually and the rest are converted using the R function `factor`. Only the households actually using electricity for space heating (identified by the variable `ELWARM` being \num{1}) are selected for the analysis, which decrceases the number of data points to \num{6154}.


# Methods


# Results


# Discussion


# Conclusions

The chosen dataset poses some difficult challenges in constructing a prediction model. The large number of categorical variables makes linear model selection hard. Neither tree models nor linear models are able to predict electricity demand for space heating in a very convincing way, but the tree-type models seem tot suit the structure of the data better. The linear model is more stable when it comes to variable selection, but due to the number of variables and the fact that most are categorical, the selection methods attempted do not work very well.

For the continued work with this dataset in the project, there are several ways forward, for example:

- Attempt to find more specialized methods that are tree-based but better suited to this particular problem.
- Work with the data to make it more suitable for linear models, e.g. by converting ordered categorical variables to numeric variables.

\appendix

# Source code

## `clean_data.R`

\lstinputlisting{project_code/clean_data.R}


